
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	private global::Gtk.Entry postText;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView postBody;
	private global::Gtk.Button postButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Post");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 400;
		this.DefaultHeight = 400;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.postText = new global::Gtk.Entry ();
		this.postText.CanFocus = true;
		this.postText.Name = "postText";
		this.postText.IsEditable = true;
		this.postText.InvisibleChar = '●';
		this.vbox2.Add (this.postText);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.postText]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.postBody = new global::Gtk.TextView ();
		this.postBody.CanFocus = true;
		this.postBody.Name = "postBody";
		this.GtkScrolledWindow.Add (this.postBody);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
		w3.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.postButton = new global::Gtk.Button ();
		this.postButton.CanFocus = true;
		this.postButton.Name = "postButton";
		this.postButton.UseUnderline = true;
		this.postButton.Label = global::Mono.Unix.Catalog.GetString ("Post");
		this.vbox2.Add (this.postButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.postButton]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.postButton.Clicked += new global::System.EventHandler (this.SendPostToParse);
	}
}
